### ISSUE TITLE
有考虑使用主流技术栈? 如果有，有时间表吗?

### ISSUE THREAD

**Issue by jacky1193610322** [dianping/cat#1670]

**Comment by youyong205** [comment]
内部已经在做了发自我的iPhone------------------ 原始邮件 ------------------发件人: jacky1193610322  <notifications@github.com>发送时间: 2019年4月20日 10:50收件人: dianping/cat <cat@noreply.github.com>抄送: Subscribed <subscribed@noreply.github.com>主题: 回复：[dianping/cat] 有考虑使用主流技术栈，如果有，有时间表吗 (#1670)

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/dianping/cat","title":"dianping/cat","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/dianping/cat"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"有考虑使用主流技术栈，如果有，有时间表吗 (#1670)"}],"action":{"name":"View Issue","url":"https://github.com/dianping/cat/issues/1670"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/dianping/cat/issues/1670",
"url": "https://github.com/dianping/cat/issues/1670",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by jacky1193610322** [comment]
谢谢回复，有大概的时间点吗？

**Comment by wangyapu** [comment]
@jacky1193610322 最快要下半年。

**Comment by jacky1193610322** [comment]
期待，谢谢
