### ISSUE TITLE
cat client for erlang

### ISSUE THREAD

**Issue by glasses1989** [dianping/cat#1673]
hi~
  ###erlang语言的cat客户端：
https://github.com/glasses1989/erlcat

需要的话，可以贡献出来；

**Comment by youyong205** [comment]
建议提交PR发自我的iPhone------------------ Original ------------------From: GlassesMan  <notifications@github.com>Date: Mon,Apr 22,2019 3:40 PMTo: dianping/cat <cat@noreply.github.com>Cc: Subscribed <subscribed@noreply.github.com>Subject: Re: [dianping/cat] cat client for erlang (#1673)hi~
###erlang语言的cat客户端：
https://github.com/glasses1989/erlcat
需要的话，可以贡献出来；

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/dianping/cat","title":"dianping/cat","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/dianping/cat"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"cat client for erlang (#1673)"}],"action":{"name":"View Issue","url":"https://github.com/dianping/cat/issues/1673"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/dianping/cat/issues/1673",
"url": "https://github.com/dianping/cat/issues/1673",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by wangyapu** [comment]
👍刚看了下，建议完善下API的使用文档，给我提交PR

**Comment by glasses1989** [comment]
> 👍刚看了下，建议完善下API的使用文档，给我提交PR

https://github.com/dianping/cat/pull/1694
